name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: '13.0'
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
  lint:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: brew install swiftformat
    - name: Lint
      run: swiftformat . --lint && swiftlint lint --strict
